js_main:
    filters:
        - rjsmin
    type: js
    depends:
        - scripts/*.js
    files:
        - bower_components/jquery/dist/jquery.js
        - bower_components/bootstrap/js/affix.js
        - bower_components/bootstrap/js/alert.js
        - bower_components/bootstrap/js/dropdown.js
        - bower_components/bootstrap/js/tooltip.js
        - bower_components/bootstrap/js/modal.js
        - bower_components/bootstrap/js/transition.js
        - bower_components/bootstrap/js/button.js
        - bower_components/bootstrap/js/popover.js
        - bower_components/bootstrap/js/carousel.js
        - bower_components/bootstrap/js/scrollspy.js
        - bower_components/bootstrap/js/collapse.js
        - bower_components/bootstrap/js/tab.js
        - bower_components/jPlayer/dist/jplayer/jquery.jplayer.js
        - bower_components/socket.io-client/dist/socket.io.slim.js
        - bower_components/moment/moment.js
        - bower_components/fullcalendar/dist/fullcalendar.js
        - bower_components/fullcalendar/dist/gcal.js
        - scripts/string_trim_polyfill.js
        - scripts/player.js
        - scripts/now_playing.js
        - scripts/websocket_setup.js
        - scripts/analytics.js
        - scripts/schedule.js
        - scripts/ajax_page_change.js  # keep this at the end so it can access all events

styles_main:
    filters:
        - less
        - csscompressor
    type: css
    depends:
        - styles/*.less
    files:
        - styles/main.less
