default: &defaultConfig
  flask: &flaskConfig
    name: 'WCPR'
    name_long: 'WCPR - Castle Point Radio'
    host: 'localhost'
    port: '5000'
    PREFERRED_URL_SCHEME: http  # http or https
    FREEZER_BASE_URL: 'http://www.wcpr.org/'
    FREEZER_DESTINATION: 'build'  # must match $BUILD_FOLDER in deploy.sh
    FREEZER_DESTINATION_IGNORE: ['.git*']  # allows for pushing build directory to github pages
    NOW_PLAYING_URL: 'http://127.0.0.1:5001/now_playing'  # see 740.wcpr.org repo
    DEBUG: True
    ASSETS_DEBUG: True
    calendar:
      api_key: 'AIzaSyB3uiiC1cR_5W1rF5paNQpR_quDIVnhuro'
      autodj_id: 'wcpr.org_c2mvtft9shfdmenddasmqcdmg8@group.calendar.google.com'
      shows_id: 'wcpr.org_1psqcd1ugmcg568arhf47c9lqo@group.calendar.google.com'

dev:
  <<: *defaultConfig

prod: &prodConfig
  <<: *defaultConfig
  flask:
    <<: *flaskConfig
    DEBUG: False
    ASSETS_DEBUG: False

freeze:
  <<: *prodConfig

freeze_dev:
  <<: *defaultConfig
  flask:
    <<: *flaskConfig
    DEBUG: False
    ASSETS_DEBUG: False
    PREFERRED_URL_SCHEME: https
    FREEZER_BASE_URL: 'https://wcpr740.github.io/'