default: &defaultConfig
  flask: &flaskConfig
    name: 'WCPR'
    name_long: 'WCPR - Castle Point Radio'
    host: 'localhost'
    port: '5000'
    PREFERRED_URL_SCHEME: http  # http or https
    FREEZER_BASE_URL: 'http://www.wcpr.org/'
    FREEZER_DESTINATION: 'build'
    DEBUG: True
    ASSETS_DEBUG: True

dev:
  <<: *defaultConfig

prod: &prodConfig
  <<: *defaultConfig
  flask:
    <<: *flaskConfig
    DEBUG: False
    ASSETS_DEBUG: False

freeze:
  <<: *prodConfig