# image is sourced from /static/images/staff/
# desc will be created as a regular text area
# questions will be shown as <strong>question</strong><br>answer
# HTML is preserved

- position: General Manager
  email: gm@wcpr.org
  name: Jackson Domenech
  image: jackson_domenech_2016.jpg
  questions:
    Major: Chemical Engineering
    Hometown: East Islip, NY
    Five Acts you can't go on listening without: Arctic Monkeys, Modern Baseball, Broken Bells, Death Cab for Cutie, Gorillaz
    Other Activities: Video Games, Playing Guitar, Listening to Music


- position: Programming Manager
  email: programming@wcpr.org
  name: Emma Murphy
  image: emma_murphy_2016.jpg
  questions:
    Major: Business & Technology
    Hometown: Brielle, NJ
    Five Acts You Can't Go On Listening Without: Frankie Cosmos, Mitski, The Lawrence Arms, Screaming Females, The Cure
    Other Activities: shredding, embroidering, slaughtering the patriarchy


- position: Business Manager
  email: business@wcpr.org
  name: Pratik Patel
  image: pratik_patel_2016.jpg
  questions:
    Major: Business & Technology
    Involvement: Student Worker at Stevens Audit and Advisory Services, Student Ambassador of Howe Business School, Dean's Activities List Member.
    Hobbies: Hosting Deep Space on WCPR, Binge watching tv shows
    Hometown: Salina, KS
    Five Acts You Can't Go On Listening Without: Zhu, Disclosure, Daft Punk, Major Lazer, Madeon, Jamie XX
    Song you hate to admit you like: <a href="https://www.youtube.com/watch?v=2H5uWRjFsGc">Chumbawamba - Tubthumping</a>


- position: Publicity Manager & Webmaster
  email: publicity@wcpr.org
  name: Kevin Poli
  image: kevin_poli_2017.png
  questions:
    Major: Computer Science / Visual Arts & Technology
    Hometown: North Brunswick, NJ
  description: I am the only one allowed to use the <span class="blink">&lt;blink&gt;</span> tag


- position: Station Engineer
  email: engineer@wcpr.org
  name: Tom Bloxam
  image: tom_bloxam_2017.jpg
  questions:
    Major: Music & Technology
    Hometown: Lehigh, PA & London, England
    Six Acts You Can't Go On Listening Without: Caribou, Daft Punk, Flume, War On Drugs, Mumford and Sons, Elvis Presley
    Favourite Movie: Fight Club
    Unknown Unguilty Pleasure: ABBA's Greatest Hits


- position: Office Manager
  email: office@wcpr.org
  name: Juliet Yeomans
  image: juliet_yeomans_2017.jpg
  questions:
    Major: Engineering Management
    Hometown: Northport, Long Island
    Guilty Pleasure Song: Literally any Ariana Grande song
    Four Acts You Can't Go On Listening Without: The Beatles, The National, Bon Iver, Bright Eyes
    Favorite Movie: Juno


- position: Record Librarian
  email: records@wcpr.org
  name: Noah Grande
  image: noah_grande_2017.jpg
  description: Noah enjoys long walks on the beach, making beats, sarcasm, and overthrowing the establishment.
  questions:
    Major: Music & Technology
    Hometown: Montclair, NJ
    Favorite Movie: "Speed 2: Cruise Control"


- position: WAA Liaison
  email: waa@wcpr.org
  name: Tori Davis
  image: tori_davis_2016.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Audubon, NJ
    Five bands you can't go on listening without: Joyce Manor, Wavves, glocca morra, The Promise Ring, Dogs on Acid
    Favorite TV Show to Binge Watch: Portlandia
    Other Activities: Ditching Stevens for a semester to travel around Europe.


- position: System Administrator
  email: sysadmin@wcpr.org
  name: Dylan DiGeronimo
  image: dylan_digeronimo_2017.jpg
  questions:
    Major: Computer Science
    Hometown: Budd Lake, NJ
    Favorite Movie: The Big Lebowski
    Guilty Pleasure Song: Wuthering Heights by Kate Bush
    Five Acts You Can't Go On Listening Without: Against Me!, Bon Iver, Modern Baseball, Neutral Milk Hotel, Mac DeMarco
    Other Activities: Playing guitar, drinking LaCroix, pronouncing space "spa-ché"
