# image is sourced from /static/images/staff/
# desc will be created as a regular text area
# questions will be shown as <strong>question</strong><br>answer
# HTML is preserved

- position: General Manager
  email: gm@wcpr.org
  name: Andy Waldron
  image: andy_waldron_2016.jpg
  questions:
    Major: Music & Technology, Visual Arts & Technology Minor
    Hometown: Fair Haven, NJ
    Five Acts You Can't Go On Listening Without: David Bowie, Beck, J Dilla, Frank Ocean, Blur
    Favorite Movie: I'm Here, Spike Jonze
    Other Activities: Making playlists, puns, emails, talking about Kanye West, and long walks on the beach. In that order.


- position: General Manager
  email: gm@wcpr.org
  name: Jackson Domenech
  image: jackson_domenech_2016.jpg
  questions:
    Major: Chemical Engineering
    Hometown: East Islip, NY
    Five Acts you can't go on listening without: Arctic Monkeys, Modern Baseball, Broken Bells, Death Cab for Cutie, Gorillaz
    Other Activities: Video Games, Playing Guitar, Listening to Music


- position: Programming Manager
  email: programming@wcpr.org
  name: David Stein
  image: david_stein_2016.jpg
  questions:
    Major: Chemical Engineering
    Hometown: Andover, MA
    Five Acts You Can't Go On Listening Without: Led Zeppelin, Spoon, The Strokes, Franz Ferdinand, Arctic Monkeys
    Other Activities: Being Dave


- position: Programming Manager
  email: programming@wcpr.org
  name: Emma Murphy
  image: emma_murphy_2016.jpg
  questions:
    Major: Business & Technology
    Hometown: Brielle, NJ
    Five Acts You Can't Go On Listening Without: Frankie Cosmos, Mitski, The Lawrence Arms, Screaming Females, The Cure
    Other Activities: shredding, embroidering, slaughtering the patriarchy


- position: Business Manager
  email: business@wcpr.org
  name: Pratik Patel
  image: pratik_patel_2016.jpg
  questions:
    Major: Business & Technology
    Involvement: Student Worker at Stevens Audit and Advisory Services, Student Ambassador of Howe Business School, Dean's Activities List Member.
    Hobbies: Hosting Deep Space on WCPR, Binge watching tv shows
    Hometown: Salina, KS
    Five Acts You Can't Go On Listening Without: Zhu, Disclosure, Daft Punk, Major Lazer, Madeon, Jamie XX
    Song you hate to admit you like: <a href="https://www.youtube.com/watch?v=2H5uWRjFsGc">Chumbawamba - Tubthumping</a>


- position: Publicity Manager & Webmaster
  email: publicity@wcpr.org
  name: Kevin Poli
  image: kevin_poli_2017.png
  questions:
    Major: Computer Science / Visual Arts & Technology
    Hometown: North Brunswick, NJ
    Favorite Movie: Clerks
    Five Acts You Can't Go On Listening Without: American Football, Car Seat Headrest, Kanye West, Elliott Smith, MF DOOM
    Other Activities: Filmmaking, Browsing Sites on The Net&trade;, Guitar, Philosophy


- position: Station Engineer
  email: engineer@wcpr.org
  name: Tom Bloxam
  image: tom_bloxam_2017.jpg
  questions:
    Major: Music & Technology
    Hometown: Lehigh, PA & London, England
    Six Acts You Can't Go On Listening Without: Caribou, Daft Punk, Flume, War On Drugs, Mumford and Sons, Elvis Presley
    Favourite Movie: Fight Club
    Unknown Unguilty Pleasure: ABBA's Greatest Hits


- position: Office Manager
  email: office@wcpr.org
  name: Juliet Yeomans
  image: juliet_yeomans_2017.jpg
  questions:
    Major: Engineering Management
    Hometown: Northport, Long Island
    Guilty Please Song: Literally any Ariana Grande song
    Four Acts You Can't Go On Listening Without: The Beatles, The National, Bon Iver, Bright Eyes
    Favorite Movie: Juno


- position: Record Librarian
  email: records@wcpr.org
  name: Brian Madden
  image: brian_madden_2016.jpg
  questions:
    Major: Electrical Engineering
    Hometown: Jackson, NJ
    Five Acts You Can't Go On Listening Without: St. Vincent, Mac DeMarco, Gorillaz, King Khan, Death Grips
    Favorite Movie: Drive
    Song you hate to admit you like: <a href="https://www.youtube.com/watch?v=O-zpOMYRi0w">Fancy by Iggy Azalea</a>
    Other Activities: Reading, Playing Music, Video Games


- position: Record Librarian
  email: records@wcpr.org
  name: Noah Grande
  image: noah_grande_2017.jpg
  description: Noah enjoys long walks on the beach, making beats, sarcasm, and overthrowing the establishment.
  questions:
    Major: Music & Technology
    Hometown: Montclair, NJ
    Favorite Movie: "Speed 2: Cruise Control"


- position: WAA Liaison
  email: waa@wcpr.org
  name: Gianluca Borrelli
  image: gianluca_borrelli_2016.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Rockway, NJ
    Five acts You Can't Go On Listening Without: Snoop Dogg, Modern Baseball, Protest the Hero, Tessaract, Kendrick Lamar
    Favorite Movie: The Notebook
    Song you hate to admit you like: <a href="https://www.youtube.com/watch?v=kT3OQwyvKmk">U Guessed It - OG Maco</a>
    Other Activities: going to concerts, skiing, netflix n' chill, satanic rituals, paganism, bible study


- position: WAA Liaison
  email: waa@wcpr.org
  name: Tori Davis
  image: tori_davis_2016.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Audubon, NJ
    Five bands you can't go on listening without: Joyce Manor, Wavves, glocca morra, The Promise Ring, Dogs on Acid
    Favorite TV Show to Binge Watch: Portlandia
    Other Activities: Ditching Stevens for a semester to travel around Europe.


- position: System Administrator & Webmaster
  email: sysadmin@wcpr.org
  name: Dylan Praul
  image: dylan_praul_2016.jpg
  description: Eventually this website won't be <a href="https://www.youtube.com/watch?v=ussCHoQttyQ">mediocre</a>.
  questions:
    Major: Computer Engineering


- position: System Administrator
  email: sysadmin@wcpr.org
  name: Dylan DiGeronimo
  image: dylan_digeronimo_2017.jpg
  questions:
    Major: Computer Science
    Hometown: Budd Lake, NJ
    Guilty Please Song: Wuthering Height by Kate Bush
    Five Acts You Can't Go On Listening Without: Against Me!, Bon Iver, Modern Baseball, Neutral Milk Hotel, Mac DeMarco
    Other Activities: Playing guitar, drinking LaCroix, pronouncing space "spa-ché"