language: python
cache: pip
python:
- '2.7'

notifications:
  email: false
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: always
    on_failure: always

install:
- npm install -g bower -g less
- bower install
- pip install -r requirements.txt

script: python freeze.py freeze_gh_pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  repo: wcpr740/wcpr740.github.io
  target_branch: master
  local_dir: build
  email: webmaster@wcpr.org
  name: WCPR Webmaster
  on:
    branch: develop