language: python
cache: pip
python:
- '2.7'

before_install:
- openssl aes-256-cbc -K $encrypted_8a5d0dfc5b11_key -iv $encrypted_8a5d0dfc5b11_iv -in deploy_key.enc -out deploy_key -d

install:
- npm install -g bower -g less
- bower install
- pip install -r requirements.txt

script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "sysadmin@wcpr.org"