language: python
cache: pip
python:
- '2.7'

before_install:
- openssl aes-256-cbc -K $encrypted_dc06db4ca05f_key -iv $encrypted_dc06db4ca05f_iv -in deploy_key.enc -out deploy_key -d

install:
- npm install -g bower -g less
- bower install
- pip install -r requirements.txt

script: freeze.py freeze_gh_pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  repo: wcpr740/wcpr740.github.io
  target_branch: master
  local_dir: build
  email: webmaster@wcpr.org
  name: WCPR Webmaster
  on:
    branch: master